import os
import sys
from Ui.newOpen import Ui_newOpen
from Ui.newProject import Ui_newProject
from Ui.mainMenu import Ui_mainMenu
from PyQt5 import QtWidgets

class openApp():
    def __init__(self):
        super(openApp, self).__init__()
        self.app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_newOpen()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        
        self.checkForButton()
        
        self.app.exec()
        
    def checkForButton(self):
        self.ui.pushButton.clicked.connect(self.openNewProj)
        
    def openNewProj(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_newProject()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        
        self.checkForGenerate()
        
    def checkForGenerate(self):
        self.ui.pushButton.clicked.connect(self.generate)

    def generate(self):
        
        # Generate Namespace, Data, Minecraft, Pack.mcmeta, etc.
        
        script_directory = os.path.dirname(os.path.abspath(sys.argv[0]))
        self.name = os.path.join(script_directory, self.ui.lineEdit_2.text())
        os.mkdir(self.name)
        os.mkdir(self.name + "\\data")
        self.namespace = os.path.join(self.name, "data", self.ui.lineEdit.text())
        self.minecraft = os.path.join(self.name, "data", "minecraft")
        os.mkdir(self.minecraft)
        os.mkdir(self.namespace)
        with open(f'{self.name}\\pack.mcmeta', 'w') as pack:
            pack.write('{\n    "pack": {\n        "pack_format": 15,\n        "description": "Generated by Python"\n    }\n}\n')
            pack.close()
            
        # Generate Basic Namespace Folders
        
        os.mkdir(self.namespace + "\\functions")
        os.mkdir(self.namespace + "\\loot_tables")
        os.mkdir(self.namespace + "\\structures")
        os.mkdir(self.namespace + "\\worldgen")
        os.mkdir(self.namespace + "\\advancements")
        os.mkdir(self.namespace + "\\recipes")
        os.mkdir(self.namespace + "\\tags")
        os.mkdir(self.namespace + "\\predicates")
        os.mkdir(self.namespace + "\\dimension")
        os.mkdir(self.namespace + "\\dimension_type")
        
        # Generate Advanced Namespace Subfolders
        
        if self.ui.comboBox.currentText() == 'Advanced Mode':
            os.mkdir(self.namespace + "\\worldgen\\noise_settings")
            os.mkdir(self.namespace + "\\worldgen\\biome")
            os.mkdir(self.namespace + "\\worldgen\\configured_carver")
            os.mkdir(self.namespace + "\\worldgen\\template_pool")
            os.mkdir(self.namespace + "\\worldgen\\structure")
            os.mkdir(self.namespace + "\\worldgen\\structure_set")
            os.mkdir(self.namespace + "\\worldgen\\processor_list")
        
            os.mkdir(self.namespace + "\\tags\\blocks")
            os.mkdir(self.namespace + "\\tags\\fluids")
            os.mkdir(self.namespace + "\\tags\\items")
            os.mkdir(self.namespace + "\\tags\\entity_types")
            os.mkdir(self.namespace + "\\tags\\game_events")
            os.mkdir(self.namespace + "\\tags\\worldgen")
            os.mkdir(self.namespace + "\\tags\\functions")
            os.mkdir(self.namespace + "\\tags\\loot_tables")
            os.mkdir(self.namespace + "\\tags\\structures")
            os.mkdir(self.namespace + "\\tags\\advancements")
            os.mkdir(self.namespace + "\\tags\\recipes")
            os.mkdir(self.namespace + "\\tags\\tags")
            os.mkdir(self.namespace + "\\tags\\predicates")
            os.mkdir(self.namespace + "\\tags\\dimension")
            
            os.mkdir(self.namespace + "\\tags\\worldgen\\noise_settings")
            os.mkdir(self.namespace + "\\tags\\worldgen\\biome")
            os.mkdir(self.namespace + "\\tags\\worldgen\\configured_carver")
            os.mkdir(self.namespace + "\\tags\\worldgen\\template_pool")
            os.mkdir(self.namespace + "\\tags\\worldgen\\structure")
            os.mkdir(self.namespace + "\\tags\\worldgen\\structure_set")
            os.mkdir(self.namespace + "\\tags\\worldgen\\processor_list")
            
        # Generate Minecraft Folders
        
        os.mkdir(self.minecraft + "\\advancements")
        os.mkdir(self.minecraft + "\\loot_tables")
        os.mkdir(self.minecraft + "\\recipes")
        os.mkdir(self.minecraft + "\\structures")
        os.mkdir(self.minecraft + "\\tags")
        
        os.mkdir(self.minecraft + "\\tags" + "\\blocks")
        os.mkdir(self.minecraft + "\\tags" + "\\entity_types")
        os.mkdir(self.minecraft + "\\tags" + "\\fluids")
        os.mkdir(self.minecraft + "\\tags" + "\\game_events")
        os.mkdir(self.minecraft + "\\tags" + "\\items")
        os.mkdir(self.minecraft + "\\tags" + "\\functions")
        
        # Generate Advanced Minecraft Subfolders
        
        if self.ui.comboBox.currentText() == 'Advanced Mode':
            os.mkdir(self.minecraft + "\\advancements" + "\\adventure")
            os.mkdir(self.minecraft + "\\advancements" + "\\end")
            os.mkdir(self.minecraft + "\\advancements" + "\\husbandry")
            os.mkdir(self.minecraft + "\\advancements" + "\\nether")
            os.mkdir(self.minecraft + "\\advancements" + "\\recipes")
            os.mkdir(self.minecraft + "\\advancements" + "\\story")
        
            os.mkdir(self.minecraft + "\\loot_tables" + "\\blocks")
            os.mkdir(self.minecraft + "\\loot_tables" + "\\chests")
            os.mkdir(self.minecraft + "\\loot_tables" + "\\entities")
            os.mkdir(self.minecraft + "\\loot_tables" + "\\gameplay")
        
            os.mkdir(self.minecraft + "\\structures" + "\\bastion")
            os.mkdir(self.minecraft + "\\structures" + "\\end_city")
            os.mkdir(self.minecraft + "\\structures" + "\\fossil")
            os.mkdir(self.minecraft + "\\structures" + "\\igloo")
            os.mkdir(self.minecraft + "\\structures" + "\\nether_fossils")
            os.mkdir(self.minecraft + "\\structures" + "\\pillager_outpost")
            os.mkdir(self.minecraft + "\\structures" + "\\ruined_portal")
            os.mkdir(self.minecraft + "\\structures" + "\\shipwreck")
            os.mkdir(self.minecraft + "\\structures" + "\\underwater_ruin")
            os.mkdir(self.minecraft + "\\structures" + "\\village")
            os.mkdir(self.minecraft + "\\structures" + "\\woodland_mansion")
            
        # Generate Load and Tick files
        
        with open(f'{self.namespace}\\functions\\tick.mcfunction', 'w') as tick:
            tick.write('# Tick File. Any commands in here run every tick (20 times per second)')
            tick.close()
        with open(f'{self.namespace}\\functions\\load.mcfunction', 'w') as load:
            load.write('tellraw "Datapack Loaded"\n# Anything in here runs every time the pack is loaded.')
            load.close()
        with open(f'{self.minecraft}\\tags\\functions\\tick.json', 'w') as tickJS:
            tickJS.write('{\n    "values":[\n        ' + f'"{self.ui.lineEdit.text()}' + ':tick"\n        ]\n    }')
            tickJS.close()
        with open(f'{self.minecraft}\\tags\\functions\\load.json', 'w') as loadJS:
            loadJS.write('{\n    "values":[\n        ' + f'"{self.ui.lineEdit.text()}' + ':load"\n        ]\n    }')
            loadJS.close()
            
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_mainMenu()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        
        self.main()

    def main(self):
        pass

if __name__ == '__main__':
    openApp()